#! /bin/sh
sh $HOME/.config/bspwm/scripts/autostart.sh

bspc monitor "eDP-1" -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           1
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config focused_border_color "#98C379"
bspc config normal_border_color "#81A1C1"
bspc config active_border_color "#eceff4"
bspc config presel_feedback_color "#A3BE8C"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle      true

bspc rule -a Thunar state=floating
bspc rule -a retroarch state=floating
bspc rule -a Tlp-UI state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a copyq state=floating
