#! /bin/sh
sh $HOME/.config/bspwm/scripts/autostart.sh

bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap           3
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config focused_border_color "#88C0D0"
bspc config normal_border_color "#e6eef3"
bspc config active_border_color "#eceff4"
bspc config presel_feedback_color "#98C379"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle      true
unclutter --ignore-scrooling &

bspc rule -a Thunar state=floating
bspc rule -a Google-chrome desktop='^2'
